<table align="left">
  <td>
    <a href="https://colab.research.google.com/github/marco-canas/4_didactica_aritmetica/blob/main/modelo_general_clase_aula_invertida.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
  </td>
</table>

### [Video de apoyo a la lectura interactiva y experimental de este cuaderno]()

## [Vínculo al programa del curso:  ]()

# Modelo general de clase: [aula invertida](https://www3.gobiernodecanarias.org/medusa/ecoescuela/pedagotic/aprendizaje-invertido-flipped-classroom/)

# Fomento de la lectura literaria asociada a Ingeniería agropecuaria y licenciatura en Matemáticas y administración de empresas

[Hábitos atómicos](https://github.com/marco-canas/habitos_atomicos/blob/main/13_como_dejar_de_postergar_usando_la_regla_de_los_dos_minutos/1_13_como_dejar_de_postergar_usando_la_regla_de_los_dos_minutos.ipynb)

# Título de la clase: Realización evaluación oral, de Tareas en cuadernos Jupyter, Quiz o Parcial de selección múltiple o de preguntas cerradas.

### Objetivo de aprendizaje (Enunciar, de manera corta sencilla y clara para todos los asistentes)

* [Hipervínculo para el cuaderno de enseñanza]()

## Establecimiento de prerrequisitos conceptuales para alcanzar el objetivo de aprendizaje trazado.   

(Elabore una lista de preguntas al rededor de los conceptos que consideres necesarios para empezar la clase).  

1. 
2. 
3.

# Para el diseño de la clase tenga en cuenta algunos problemas de aprendizaje

# Diseño de evaluación oral de si se alcanzaron los objetivos de aprendizaje planteados

* Describa verbalmente el objetivo de aprendizaje y evidencie de forma oral si lo logró o no.

## Cuestionario para realizar labores de memorización, observación y síntesis de la información (Además de diagnóstico)

1. ¿?
2. ¿?
3. ¿?
4. ¿?
5. ¿?

In [1]:
# llamado a los estudiantes para participación oral en clase
import pandas as pd
import numpy as np

# Cargar la lista de estudiantes desde la URL
url = 'https://raw.githubusercontent.com/marco-canas/groups_list/main/english.csv'
estudiantes = pd.read_csv(url)

# Convertir la columna 'Nombre' a una lista de Python
lista_estudiantes = estudiantes['Nombre'].tolist()

# Función para llamar a un estudiante aleatoriamente y registrar su nota de seguimiento
def llamar_estudiante():
    if lista_estudiantes:
        estudiante_aleatorio = np.random.choice(lista_estudiantes)
        print(f"Llamando a {estudiante_aleatorio}...")
        lista_estudiantes.remove(estudiante_aleatorio)
    else:
        print("Se han llamado a todos los estudiantes del grupo completo.")

In [2]:

# Llamar a la función para realizar el proceso
llamar_estudiante()

Llamando a Maro Julio Canas...

# Componente de evaluación de las tareas realizadas en cuaderno Jupyter 

1. Tares antes de la clase: (i ejercicio asignado)
2. Tareas en clase (un ejercicio asignado)
3. Tares después de la clase (tres ejercicios asignados)

In [1]:
# asignación de ejercicios para antes de la clase

# numpy.random.choice() obten la documentación de esta función en: 
# https://numpy.org/doc/stable/reference/random/generated/numpy.random.choice.html

import pandas as pd
import numpy as np
import requests
np.random.seed(42)  # establecer semilla aleatoria para hacer los resultados reproducibles



grupo_estudiantes = 'calculo_integral'
nombre_texto_guia = 'Purcell'
pagina_y_seccion = 'Página_208_Sección_3.9'
numero_ejercicios_taller = 5
numero_de_ejercicios_asignados = 1


# Descargar la lista de  estudiantes
students_url = "https://raw.githubusercontent.com/marco-canas/groups_list/main/" + grupo_estudiantes + ".csv"
exercises = list(range(1, numero_ejercicios_taller))  

students_data = pd.read_csv(students_url)

# Crear una lista para almacenar las asignaciones
assignments = []

# Asignar ejercicios aleatorios a cada estudiante
for index, student in students_data.iterrows():
    # Seleccionar 5 ejercicios aleatorios sin repetición
    random_exercises = np.random.choice(exercises, numero_de_ejercicios_asignados, replace = False)+ 1 
    assignments.append([students_data["Nombre"][index], *random_exercises])  # Agregar asignación a la lista

# Crear un DataFrame con las asignaciones
columns = ["Student"] + [ "Example" + str(i+1) for i in range(numero_de_ejercicios_asignados)]
assignment_df = pd.DataFrame(assignments, columns=columns)

# Guardar el DataFrame en un archivo CSV
assignment_csv = "tarea" + "_" + nombre_texto_guia + "_"+ pagina_y_seccion + ".csv"
assignment_df.to_csv(assignment_csv, index=False)

print("Tarea asignada: ", assignment_csv)
assignment_df

Tarea asignada:  tarea_Purcell_Página_208_Sección_3.9.csv

                              Student  Example1
0        AGUDELO MORENO RENATO DIRNEY         3
1   AMARIS FERNANDEZ SEBASTIAN CAMILO         3
2       ARENAS HERAZO GABRIEL ENRIQUE         5
3        AYALA MENDOZA MARISOL YACIRA         3
4          BERTEL RODELO MICHELL SMIT         4
5            BULA VERGARA MARIA PAULA         2
6             CANTILLO ENSUCHO DANIEL         5
7            CERVANTES DURAN ANGELICA         2
8         GALLEGO TEJADA JUAN ESTEBAN         5
9             GUERRA NORIEGA YONATHAN         2
10    HINCAPIE CASTRO JOHAN SEBASTIAN         3
11             HUMANEZ SANCHEZ CAMILO         3
12       IBAnEZ MORENO FRANCISCO LUIS         2
13  LONDONO CUADRADO CRISTIAN ALBERTO         2
14          MASS MIRANDA RIVALDO JOSE         2
15     MIRANDA MARTINEZ CARLOS ANDRES         3
16              MONTERROSA SOTO ABRIL         3
17           NORIEGA JIMENEZ GABRIELA         3
18             PEREZ REYES IVAN DARIO         4
19               PEREZ THERAN ERLINDA         2
20              PINEDA ROMERO YOSMERI         4
21         QUINONEZ CERVANTES MARIANA         2
22           QUIROZ DURAN JUAN MANUEL         5
23                 RAMOS PEREZ YANINE         2
24              RIVAS HOYOS ESTEFANIA         5
25              ROSILLO TEJADA VANESA         2
26          SANCHEZ PADILLA SILVESTRE         2
27        SILVA ROYERO MAILY CRISTINA         4
28          USUGA GEORGE JHON ESTIVEN         2

In [2]:
# asignación de ejercicio para realizar en clase

# numpy.random.choice() obten la documentación de esta función en: 
# https://numpy.org/doc/stable/reference/random/generated/numpy.random.choice.html

import pandas as pd
import numpy as np
import requests
np.random.seed(42)  # establecer semilla aleatoria para hacer los resultados reproducibles



grupo_estudiantes = 'calculo_integral'
nombre_texto_guia = 'Purcell'
pagina_y_seccion = 'Página_208_Sección_3.9'
numero_ejercicios_taller = 37
numero_de_ejercicios_asignados = 1


# Descargar la lista de  estudiantes
students_url = "https://raw.githubusercontent.com/marco-canas/groups_list/main/" + grupo_estudiantes + ".csv"
exercises = list(range(1, numero_ejercicios_taller))  

students_data = pd.read_csv(students_url)

# Crear una lista para almacenar las asignaciones
assignments = []

# Asignar ejercicios aleatorios a cada estudiante
for index, student in students_data.iterrows():
    # Seleccionar 5 ejercicios aleatorios sin repetición
    random_exercises = np.random.choice(exercises, numero_de_ejercicios_asignados, replace = False)+ 1 
    assignments.append([students_data["Nombre"][index], *random_exercises])  # Agregar asignación a la lista

# Crear un DataFrame con las asignaciones
columns = ["Student"] + [ "Exercise" + str(i+1) for i in range(numero_de_ejercicios_asignados)]
assignment_df = pd.DataFrame(assignments, columns=columns)

# Guardar el DataFrame en un archivo CSV
assignment_csv = "tarea" + "_" + nombre_texto_guia + "_"+ pagina_y_seccion + ".csv"
assignment_df.to_csv(assignment_csv, index=False)

print("Tarea asignada: ", assignment_csv)
assignment_df

Tarea asignada:  tarea_Purcell_Página_208_Sección_3.9.csv

                              Student  Exercise1
0        AGUDELO MORENO RENATO DIRNEY         37
1   AMARIS FERNANDEZ SEBASTIAN CAMILO         17
2       ARENAS HERAZO GABRIEL ENRIQUE          3
3        AYALA MENDOZA MARISOL YACIRA         12
4          BERTEL RODELO MICHELL SMIT         28
5            BULA VERGARA MARIA PAULA         24
6             CANTILLO ENSUCHO DANIEL         14
7            CERVANTES DURAN ANGELICA         27
8         GALLEGO TEJADA JUAN ESTEBAN         32
9             GUERRA NORIEGA YONATHAN         32
10    HINCAPIE CASTRO JOHAN SEBASTIAN         35
11             HUMANEZ SANCHEZ CAMILO          4
12       IBAnEZ MORENO FRANCISCO LUIS         11
13  LONDONO CUADRADO CRISTIAN ALBERTO         25
14          MASS MIRANDA RIVALDO JOSE          8
15     MIRANDA MARTINEZ CARLOS ANDRES         28
16              MONTERROSA SOTO ABRIL         33
17           NORIEGA JIMENEZ GABRIELA         25
18             PEREZ REYES IVAN DARIO         16
19               PEREZ THERAN ERLINDA         33
20              PINEDA ROMERO YOSMERI          5
21         QUINONEZ CERVANTES MARIANA         21
22           QUIROZ DURAN JUAN MANUEL         30
23                 RAMOS PEREZ YANINE         23
24              RIVAS HOYOS ESTEFANIA         14
25              ROSILLO TEJADA VANESA         35
26          SANCHEZ PADILLA SILVESTRE         12
27        SILVA ROYERO MAILY CRISTINA         15
28          USUGA GEORGE JHON ESTIVEN         25

In [3]:
# asignación de tres ejercicios para después de realizada la clase

# numpy.random.choice() obten la documentación de esta función en: 
# https://numpy.org/doc/stable/reference/random/generated/numpy.random.choice.html

import pandas as pd
import numpy as np
import requests
np.random.seed(42)  # establecer semilla aleatoria para hacer los resultados reproducibles



grupo_estudiantes = 'calculo_integral'
nombre_texto_guia = 'Purcell'
pagina_y_seccion = 'Página_208_Sección_3.9'
numero_ejercicios_taller = 37
numero_de_ejercicios_asignados = 3


# Descargar la lista de  estudiantes
students_url = "https://raw.githubusercontent.com/marco-canas/groups_list/main/" + grupo_estudiantes + ".csv"
exercises = list(range(1, numero_ejercicios_taller))  

students_data = pd.read_csv(students_url)

# Crear una lista para almacenar las asignaciones
assignments = []

# Asignar ejercicios aleatorios a cada estudiante
for index, student in students_data.iterrows():
    # Seleccionar 5 ejercicios aleatorios sin repetición
    random_exercises = np.random.choice(exercises, numero_de_ejercicios_asignados, replace = False)+ 1 
    assignments.append([students_data["Nombre"][index], *random_exercises])  # Agregar asignación a la lista

# Crear un DataFrame con las asignaciones
columns = ["Student"] + [ "Exercise" + str(i+1) for i in range(numero_de_ejercicios_asignados)]
assignment_df = pd.DataFrame(assignments, columns=columns)

# Guardar el DataFrame en un archivo CSV
assignment_csv = "tarea" + "_" + nombre_texto_guia + "_"+ pagina_y_seccion + ".csv"
assignment_df.to_csv(assignment_csv, index=False)

print("Tarea asignada: ", assignment_csv)
assignment_df

Tarea asignada:  tarea_Purcell_Página_208_Sección_3.9.csv

                              Student  Exercise1  Exercise2  Exercise3
0        AGUDELO MORENO RENATO DIRNEY         37         15         28
1   AMARIS FERNANDEZ SEBASTIAN CAMILO         17         18          6
2       ARENAS HERAZO GABRIEL ENRIQUE          3         12          6
3        AYALA MENDOZA MARISOL YACIRA         12         30          5
4          BERTEL RODELO MICHELL SMIT         28         32         22
5            BULA VERGARA MARIA PAULA         24         35          5
6             CANTILLO ENSUCHO DANIEL         14         17         21
7            CERVANTES DURAN ANGELICA         27         25         24
8         GALLEGO TEJADA JUAN ESTEBAN         32         22         14
9             GUERRA NORIEGA YONATHAN         32          8         11
10    HINCAPIE CASTRO JOHAN SEBASTIAN         35         13          6
11             HUMANEZ SANCHEZ CAMILO          4         30         27
12       IBAnEZ MORENO FRANCISCO LUIS         11         32          5
13  LONDONO CUADRADO CRISTIAN ALBERTO         25         10         19
14          MASS MIRANDA RIVALDO JOSE          8         30          7
15     MIRANDA MARTINEZ CARLOS ANDRES         28         15          7
16              MONTERROSA SOTO ABRIL         33         22          3
17           NORIEGA JIMENEZ GABRIELA         25         22         33
18             PEREZ REYES IVAN DARIO         16         18         27
19               PEREZ THERAN ERLINDA         33         27         14
20              PINEDA ROMERO YOSMERI          5         34         13
21         QUINONEZ CERVANTES MARIANA         21         12         32
22           QUIROZ DURAN JUAN MANUEL         30          5         36
23                 RAMOS PEREZ YANINE         23         19          2
24              RIVAS HOYOS ESTEFANIA         14          5          9
25              ROSILLO TEJADA VANESA         35         18         30
26          SANCHEZ PADILLA SILVESTRE         12         24         15
27        SILVA ROYERO MAILY CRISTINA         15         36          8
28          USUGA GEORGE JHON ESTIVEN         25         22         10

In [ ]:
# Ejemplo de quiz
# Este es un código python para elegir puntos a evaluar de manera aleatoria
# asignación de tres ejercicio del taller para quiz

import pandas as pd
import numpy as np

np.random.randint(37)


# Proponemos que los estudiantes puedan utilizar para el quiz, a la librería sympy.

In [4]:
# Este es un código python para llamar a estudiantes para ser evaluados en una prueba quiz
import pandas as pd
import random

# Cargar la lista de estudiantes desde la URL
url = 'https://raw.githubusercontent.com/marco-canas/groups_list/main/seminario_didactica_aritmetica.csv'
estudiantes = pd.read_csv(url)

# Función para llamar a un estudiante aleatoriamente y registrar su nota de seguimiento
def llamar_estudiante():
    estudiante_aleatorio = random.choice(estudiantes['Nombre'])
    print(f"Llamando a {estudiante_aleatorio}...")
    
    
# Llamar a la función para realizar el proceso
llamar_estudiante()

Llamando a ARIAS ARRIETA FREDY...

# Programa para evaluación del seguimiento mensual de los estudiantes

In [7]:
# Programa para valoración cuantitativa por meses para los estudiantes de todos los cursos
import numpy as np 
import pandas as pd   

#weights
weightAssistance = 12/100
weightAttentionParticipation = 8/100
weightHandwrittenNotebook = 8/100
weightJupyterNotebook = 20/100
weightQuiz = 16/100
weightPartial = 48/100

url_group = 'https://raw.githubusercontent.com/marco-canas/groups_list/main/seminario_didactica_aritmetica.csv'

df = pd.read_csv(url_group, decimal = ',') 

df.Assistance = (df.Assistance/np.max(df.Assistance))*5.0
df.AttentionParticipation = (df.AttentionParticipation/np.max(df.AttentionParticipation))*5.0
df.HandwrittenNotebook = (df.HandwrittenNotebook/np.max(df.HandwrittenNotebook))*5.0
df.JupyterNotebook = (df.JupyterNotebook/np.max(df.JupyterNotebook))*5.0  


df['FollowUp'] = df.Assistance*weightAssistance + \
                 df.AttentionParticipation*weightAttentionParticipation + \
                 df.HandwrittenNotebook*weightHandwrittenNotebook+\
                 df.JupyterNotebook*weightJupyterNotebook+\
                 df.Quiz*weightQuiz + \
                 df.Partial*weightPartial

df.FollowUp = df.FollowUp.round(1)

df[['Nombre', 'FollowUp']]

AttributeError: 'DataFrame' object has no attribute 'AttentionParticipation'

<img src = ''>

## Tareas para realizar antes de la clase

1. Ver los videos respectivos []()
2. Memorizar las definiciones []()
3. Sintetizar o resumir la información en mapas conceptuales. []()

# Tareas para realizar en clase

* Modelación matemática 
* Trabajo en equipos

# Tareas para realizar después de la realización de la clase

* Actividades de memorización: 
  - escucha reiterada de grabaciones de formulas y resultados científicos. 
  - relectura de notas. 
  - ejercicios de mayor complejidad.

In [3]:
# asignación de tres ejercicio del taller para quiz

import pandas as pd
import numpy as np
import random
import requests
np.random.seed(42)
# Descargar la lista de  estudiantes y ejercicios
students_url = "https://raw.githubusercontent.com/marco-canas/groups_list/main/fund_math.csv"
exercises = list(range(1, 135))  # Lista de ejercicios del 1 al 83

# Cargar la lista de estudiantes
students_data = pd.read_csv(students_url)

# Crear una lista para almacenar las asignaciones
assignments = []

# Asignar ejercicios aleatorios a cada estudiante
for index, student in students_data.iterrows():
    random_exercises = random.sample(exercises, 20)  # Seleccionar 5 ejercicios aleatorios sin repetición
    assignments.append([students_data["Nombre"][index], *random_exercises])  # Agregar asignación a la lista

# Crear un DataFrame con las asignaciones
columns = ["Student", "Exer1", "Exer2", "Exer3","Exer4", "Exer5", \
           "Exercise 6", "Exercise 7", "Exercise 8", "Exercise 9", "exercise 10", \
           "Exer11", "Exer12", "Exer13","Exer14", "Exer15", \
           "Exer16", "Exer17", "Exer18", "Exer19", "exer20"
            ]
assignment_df = pd.DataFrame(assignments, columns=columns)

# Guardar el DataFrame en un archivo CSV
assignment_csv = "tarea_seccion_1_3:precalculo_stewart.csv"
assignment_df.to_csv(assignment_csv, index=False)

print("Asignaciones guardadas en", assignment_csv)
assignment_df

Asignaciones guardadas en tarea_seccion_1_3:precalculo_stewart.csv

,Student,Exer1,Exer2,Exer3,Exer4,Exer5,Exercise 6,Exercise 7,Exercise 8,Exercise 9,...,Exer11,Exer12,Exer13,Exer14,Exer15,Exer16,Exer17,Exer18,Exer19,exer20
0,ARIAS ARRIETA FREDY,29,96,110,40,63,120,75,105,34,...,111,22,11,131,44,69,20,90,13,60
1,BOHORQUEZ NAVARRO DINA ESTELA,32,15,120,39,114,95,85,42,6,...,74,124,52,89,79,99,47,11,132,111
2,CARDONA RAM�REZ SARA PAULINA,62,12,107,13,79,68,112,18,64,...,131,93,90,103,116,69,100,51,35,48
3,CASTANEDA REINOZA DIEGO,119,25,1,43,48,81,107,38,97,...,72,18,89,30,109,10,8,34,2,7
4,ESPEJO PEREZ LUIS DAVID,30,6,96,74,126,75,26,11,71,...,42,91,79,49,10,95,34,61,103,62
5,HERNANDEZ GUERRA FABIAN ALEJANDRO,97,8,84,89,120,36,95,131,126,...,1,72,19,67,128,49,24,57,51,48
6,HERRERA PAYARES RAFAEL ANTONIO,57,71,22,87,124,67,51,65,56,...,47,24,41,121,131,80,110,2,13,123
7,LUCAS FLOREZ NAYELIS NATALIA,122,55,110,121,117,32,72,53,40,...,73,130,126,12,105,13,64,83,100,59
8,MARTINEZ BALLESTEROS VICTOR HUGO,73,67,62,120,71,55,101,43,51,...,8,110,111,121,32,45,98,85,127,125
9,MARTINEZ MENDOZA JAIR MIGUEL,53,57,119,75,55,104,86,126,7,...,30,134,109,17,87,70,47,18,22,40
10,MAZO PEREZ SAMUEL,132,110,31,133,65,25,34,109,28,...,35,101,85,22,125,103,4,77,37,124
11,MONTES DIAZ DIEGO ALEJANDRO,120,134,43,68,77,52,89,73,63,...,94,131,34,37,25,106,123,15,35,39
12,OCHOA ARRIETA JUAN ANDRES,61,23,41,1,122,30,59,33,5,...,107,31,36,120,119,65,132,70,103,71
13,RUIZ CARDENAS LUIS MARIO,34,57,1,68,113,79,67,39,75,...,71,11,122,78,61,101,66,126,83,52
14,SIERRA OLIVEROS OMAR DARIO,67,59,68,5,92,116,129,34,62,...,35,107,48,7,120,12,27,126,64,82
15,SUAREZ RESTREPO MARIA ANGELICA,58,102,92,91,105,78,80,101,49,...,30,1,34,62,46,65,42,128,31,113
16,TAMAYO DE LA OSSA SARA,79,38,15,122,70,110,9,12,78,...,33,82,87,32,22,131,52,8,126,7

## Estrategias propuestas para la solución de las dificultades de aprendizaje detectadas

## Cuestionario para realizar labores de memorización y observación,  a la síntesis de la información

## Grabaciones en audio para fomentar la capacidad de memorizar enunciados de teoremas y resultados científicos y la capacidad de parafrasear estos resultados.

Se dispondrá de un lugar en el drive asociuado al correo institucional de la Universidad Nacional del Profesor Marso para albergar los archivosd de audio de fomento a la memoirización, enunciación y parafraseo de los resultados científicos, prtopiedades, reglas, etc. 

* Vocaroo

### Comparta sus cuadernos y videos, evidencias de su aprendizaje [aquí](https://forms.office.com/Pages/ResponsePage.aspx?id=IefhmYRxjkmK_7KtTlPBwkanXIs1i1FEujpsZgO6dXpUMEMwTEZVMzEwVVBPTElWNVg5OVEyWUhMUy4u)

# Vocabulary

# FODA del grupo y del profesor  

* F: Fortalezas
* O: Oportunidades
* D: Dificultades
* A: Amenazas.

## ¿Cómo se sintió en este espacio de enseñanza y aprendizaje?

!Dios te bendiga¡

In [15]:
# Programa para valoración cuantitativa por meses para los estudiantes de todos los cursos
import numpy as np 
import pandas as pd   

# Weights
weightAssistance = 12/100
weightAttentionParticipation = 8/100
weightHandwrittenNotebook = 8/100
weightJupyterNotebook = 20/100
weightQuiz = 16/100
weightPartial = 48/100

url_group = 'https://raw.githubusercontent.com/marco-canas/groups_list/main/calculo_integral.csv'

df = pd.read_csv(url_group, decimal = ',') 

df.Assistance = (df.Assistance/np.max(df.Assistance))*5.0
df.AttentionParticipation = (df.AttentionParticipation/np.max(df.AttentionParticipation))*5.0
df.HandwrittenNotebook = (df.HandwrittenNotebook/np.max(df.HandwrittenNotebook))*5.0
df.JupyterNotebook = (df.JupyterNotebook/np.max(df.JupyterNotebook))*5.0  


df['FollowUp'] = np.round(df.Assistance*weightAssistance+\
    df.AttentionParticipation*weightAttentionParticipation+\
    df.HandwrittenNotebook*weightHandwrittenNotebook+\
    df.JupyterNotebook*weightJupyterNotebook+\
    df.Quiz*weightQuiz+\
    df.Partial*weightPartial,1)
df[['Nombre', 'FollowUp']]

                               Nombre  FollowUp
0        AGUDELO MORENO RENATO DIRNEY       2.8
1   AMARIS FERNANDEZ SEBASTIAN CAMILO       2.5
2       ARENAS HERAZO GABRIEL ENRIQUE       2.5
3        AYALA MENDOZA MARISOL YACIRA       2.7
4          BERTEL RODELO MICHELL SMIT       2.5
5            BULA VERGARA MARIA PAULA       2.5
6             CANTILLO ENSUCHO DANIEL       5.0
7            CERVANTES DURAN ANGELICA       3.4
8         GALLEGO TEJADA JUAN ESTEBAN       1.9
9             GUERRA NORIEGA YONATHAN       4.6
10    HINCAPIE CASTRO JOHAN SEBASTIAN       3.8
11             HUMANEZ SANCHEZ CAMILO       4.7
12       IBAnEZ MORENO FRANCISCO LUIS       3.5
13  LONDONO CUADRADO CRISTIAN ALBERTO       2.0
14       LOZANO HOLGUIN LIZETH JOHANA       3.4
15          MASS MIRANDA RIVALDO JOSE       4.6
16     MIRANDA MARTINEZ CARLOS ANDRES       3.8
17              MONTERROSA SOTO ABRIL       2.6
18           NORIEGA JIMENEZ GABRIELA       2.2
19             PEREZ REYES IVAN DARIO       2.3
20               PEREZ THERAN ERLINDA       2.8
21              PINEDA ROMERO YOSMERI       4.1
22         QUINONEZ CERVANTES MARIANA       2.4
23           QUIROZ DURAN JUAN MANUEL       1.8
24                 RAMOS PEREZ YANINE       2.7
25              RIVAS HOYOS ESTEFANIA       2.3
26              ROSILLO TEJADA VANESA       4.8
27          SANCHEZ PADILLA SILVESTRE       4.8
28        SILVA ROYERO MAILY CRISTINA       2.1
29          USUGA GEORGE JHON ESTIVEN       3.9

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Nombre                  30 non-null     object
 1   Email                   30 non-null     object
 2   AttentionParticipation  30 non-null     float64
 3   JupyterNotebook         30 non-null     float64
 4   Partial                 30 non-null     float64
 5   Quiz                    30 non-null     float64
 6   HandwrittenNotebook     30 non-null     float64
 7   Assistance              30 non-null     float64
dtypes: float64(6), object(2)
memory usage: 2.0+ KB

## Referentes

* [stewart precálculo](https://udeaeduco-my.sharepoint.com/:b:/g/personal/marco_canas_udea_edu_co/ERHIq62I6qFNrmxy6LZb8ZMBci7kUsyNME1nIh9yCBMJ_w?e=0zMSla)  

* [stewart cálculo](https://udeaeduco-my.sharepoint.com/:b:/g/personal/marco_canas_udea_edu_co/EZgXZjAp8QxPqOAim2hs6LcBNPLGjSHf-xwYnUVYkwa04w?e=RZdTCy)  

* [larson](https://udeaeduco-my.sharepoint.com/:b:/g/personal/marco_canas_udea_edu_co/ES71ChFeO9ZDhW3TwC5Ijk8BjxUK3Pdqz_fjHxTTFAfIAg?e=VDEjfu)

* [uzcategui](https://udeaeduco-my.sharepoint.com/:b:/g/personal/marco_canas_udea_edu_co/ETDikm-lVl1Or8XoEo9oyh0BEti9Zs8le-f0D-dBdtZmbA?e=bBsoyQ)

* [Recomendación de la UNESCO sobre ciencia abierta](https://unesdoc.unesco.org/ark:/48223/pf0000379949_spa)  

* [chatGPT](https://openai.com/blog/chatgpt)  

* Géron, A. (2017). Hands-on machine learning with scikit-learn and tensorflow: Concepts. Tools, and Techniques to build intelligent systems.[Geron, Aurelien. Hands on Machine Learning](https://udeaeduco-my.sharepoint.com/:b:/g/personal/marco_canas_udea_edu_co/Ecet27yjQzZIlT1Y_Bc2erkBUhbeYuIe6HG8i1FYZRlZww?e=dlvZ4v)  

* McKinney, W. (2012). Python for data analysis: Data wrangling with Pandas, NumPy, and IPython. " O'Reilly Media, Inc.".[Wes Mackinney. ](https://udeaeduco-my.sharepoint.com/:b:/g/personal/marco_canas_udea_edu_co/EVbi5JIeBl9ErbiUnZfGe8YBhNTnZ8sxTK5hjIOPK4UpGw?e=fFclah)

### [Evaluamos al profesor Marco Cañas Aquí](https://forms.office.com/Pages/ResponsePage.aspx?id=IefhmYRxjkmK_7KtTlPBwkanXIs1i1FEujpsZgO6dXpUREJPV1kxUk1JV1ozTFJIQVNIQjY5WEY3US4u)

## [Evaluación luego de alcanzar estos objetivos de aprendizaje]()

### Continue su aprendizaje en la siguiente clase a través del siguiente [vínculo]()

# Conjeturas pedagógicas fruto de la aplicación del modelo de aprendizaje invertido y del enfoque hacia la ciencia de datos con python

1. Todo cálculo o resultado debe ser interpretado en una línea markdown del cuaderno Jupyter, inmediatamente después de la enunciación del resultado y después de la presentación de una tabla o gráfico bidimensional, de tal menera que el estudiante explicite la comprensión verbal del resultado y las inferencias o estrategias que este resultado le sugieren.